//Requests para la tabla "mascota"

### Crear una nueva mascota (POST)
POST http://localhost:4000/mascotas/crear
Content-Type: application/json

### Buscar todas las mascotas (GET)
GET http://localhost:4000/mascotas/buscar

### Buscar una mascota por ID (GET)
GET http://localhost:4000/mascotas/buscarId/

### Actualizar una mascota (PUT)
PUT http://localhost:4000/mascotas/actualizar/
Content-Type: application/json

### Eliminar una mascota (DELETE)
DELETE http://localhost:4000/mascotas/eliminar/


////////////////////////////////////////////////////////////////////////////////////////


//Requests para la tabla "solicitud_adopcions"

### Crear una nueva solicitud de adopción (POST)
POST http://localhost:4000/solicitudes/crear
Content-Type: application/json

### Buscar todas las solicitudes de adopción (GET)
GET http://localhost:4000/solicitudes/buscar

### Buscar una solicitud de adopción por ID (GET)
GET http://localhost:4000/solicitudes/buscarId/1

### Actualizar una solicitud de adopción (PUT)
PUT http://localhost:4000/solicitudes/actualizar/1
Content-Type: application/json

### Eliminar una solicitud de adopción (DELETE)
DELETE http://localhost:4000/solicitudes/eliminar/1


////////////////////////////////////////////////////////////////////////////////////////


//Requests para la tabla "tipo de mascota"

### Crear un nuevo tipo de mascota (POST)
POST http://localhost:4000/tipos-mascotas/crear
Content-Type: application/json

### Buscar todos los tipos de mascotas (GET)
GET http://localhost:4000/tipos-mascotas/buscar

### Buscar un tipo de mascota por ID (GET)
GET http://localhost:4000/tipos-mascotas/buscarId/1

### Actualizar un tipo de mascota (PUT)
PUT http://localhost:4000/tipos-mascotas/actualizar/1
Content-Type: application/json

### Eliminar un tipo de mascota (DELETE)
DELETE http://localhost:4000/tipos-mascotas/eliminar/1


////////////////////////////////////////////////////////////////////////////////////////


//Requests para la tabla "usuarios"


### Crear un nuevo usuario (POST)
POST http://localhost:4000/usuarios/crear
Content-Type: application/json

### Buscar todos los usuarios (GET)
GET http://localhost:4000/usuarios/buscar
HTTP/1.1

### Buscar un usuario por ID (GET)
GET http://localhost:4000/usuarios/buscarId/1
HTTP/1.1

### Actualizar un usuario (PUT)
PUT http://localhost:4000/usuarios/actualizar/1
Content-Type: application/json

### Eliminar un usuario (DELETE)
DELETE http://localhost:4000/usuarios/eliminar/2                                                           
HTTP/1.1